import type { ProviderId } from './provider';

/**
 * Represents one enabled payment method returned by the backend API.
 *
 * Internal information such as owner IDs and storage paths must never
 * be included in this public object.
 */
export interface PaymentMethod {
  // Public identifier generated by the backend.
  id: string;

  // Identifies which e-wallet this payment method uses.
  provider: ProviderId;

  // Provider name displayed by the widget.
  displayName: string;

  // Name of the person or business receiving the payment.
  accountName: string;

  // Can be null when the owner chooses to hide the account number.
  accountNumber: string | null;

  // Public or temporary URL used to display the QR image.
  qrImageUrl: string;

  // Optional plain-text payment instructions.
  instructions: string | null;
}

/**
 * Represents the expected response from the payment-method endpoint.
 */
export interface PaymentMethodsResponse {
  data: PaymentMethod[];
}
